### ISSUE TITLE
Importing historical stats

### ISSUE THREAD

**Issue by 0x464e** [mkdryden/telegram-stats-bot#10]
Hi, 

Nice application, seems really cool. 
For me to use it though, I'd really need some ability to import past stats. I'm not seeing support for this being documented, so I'm assuming it's not built in. Could I manually do it somehow though?

**Comment by mkdryden** [comment]
I think I wrote a script to do it from a chat history dump from the desktop client when I set it up initially. When I get a chance, I will dig it up and see if it still works correctly.

**Comment by 0x464e** [comment]
That would be awesome, thanks.

**Comment by mkdryden** [comment]
Added in b8b8eff. I have tried it on a couple of servers, but I'm still not totally sure there aren't any problems, so I won't push a new version just yet.

**Comment by 0x464e** [comment]
Thanks man, I'll definitely check it out later
