### ISSUE TITLE
import script causes db issues

### ISSUE THREAD

**Issue by mkdryden** [mkdryden/telegram-stats-bot#17]
The import script introduced in b8b8eff (see #10) seems to be changing the types of columns in the db.
I think this has to do with using pandas to do the update.
Specifically it is breaking the `user` command because it is changing the `user_id` column to text from integer.

**Comment by mkdryden** [comment]
The problem is in this block: https://github.com/mkdryden/telegram-stats-bot/blob/f3b61b640e420c1cb3670cef6aae54cb5ad5d9af/telegram_stats_bot/json_dump_parser.py#L124-L128

When multiple people join in one event, we don't have access to their user_id, only the display name, so we will have to convert them when possible before inserting into the database, and dropping the ones that can't be mapped to an id.

**Comment by eiger8** [comment]
I faced such an error when importing simple json with 75 messages
![iTerm2 2023-01-03 at 22 50 53@2x](https://user-images.githubusercontent.com/21951841/210439497-331cfc9f-0403-43ae-bbc8-413ba599ccd9.png)

**Comment by mkdryden** [comment]
> I faced such an error when importing simple json with 75 messages ![iTerm2 2023-01-03 at 22 50 53@2x](https://user-images.githubusercontent.com/21951841/210439497-331cfc9f-0403-43ae-bbc8-413ba599ccd9.png)
> 
> @mkdryden is this something you are are mentioning in this issue?

I'm currently on vacation and I don't have access to my test system, but I will take a look at it when I get back.
It looks like a different issue though, so I have moved it to #18 
If there isn't any private information in your json dump, it would probably be useful to have to see if I can reproduce it.

**Comment by eiger8** [comment]
> > I faced such an error when importing simple json with 75 messages ![iTerm2 2023-01-03 at 22 50 53@2x](https://user-images.githubusercontent.com/21951841/210439497-331cfc9f-0403-43ae-bbc8-413ba599ccd9.png)
> > @mkdryden is this something you are are mentioning in this issue?
> 
> I'm currently on vacation and I don't have access to my test system, but I will take a look at it when I get back. It looks like a different issue though, so I have moved it to #18. If there isn't any private information in your json dump, it would probably be useful to have to see if I can reproduce it.

If you need help on debugging, etc let me know.
