### ISSUE TITLE
[IMPROVEMENT] Use short, not parameterized, commands to be able to setup BotFather bot commands shortcuts

### ISSUE THREAD

**Issue by eiger8** [mkdryden/telegram-stats-bot#25]
**IMPROVEMENT**

Using BotFathere it is possible to configure predefined commands. The problem is that it does not accept multi word commands i.e. "stats days" in configurator. 

The BotFather directive /setcommands accepted format:
command1 - Description
command2 - Another description

**Comment by mkdryden** [comment]
I think for now I will close this as I am exploring a less annoying way to use the bot using the inline keyboard functionality for selecting stats and configuring options.
