### ISSUE TITLE
ImportError: cannot import name 'Animation' from 'telegram'

### ISSUE THREAD

**Issue by hndrk-themer** [mkdryden/telegram-stats-bot#9]
After running your bot like for over 7months without problem i cant start it anymore. I literally changed nothing.

I reinstalled like stated in readme, i even did the poetry way after i couldnt get it fixed, but nothing.

On Python 3.8:

ImportError: cannot import name 'TelegramError' from 'telegram' (....

on Python 3.9:

ImportError: cannot import name 'Animation' from 'telegram' (...

**Comment by hndrk-themer** [comment]
thanks! alright the bot is running again via docker ... i totally forgot that there is a docker image.

My Homeserver runs latest and fully updated Debian. As i said before i tested under Python 3.8 and Python 3.9. 

Here is the complete Output:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/hendrik/.local/lib/python3.8/site-packages/telegram_stats_bot/main.py", line 31, in <module>
    from telegram.ext import Updater, CommandHandler, MessageHandler, Filters, CallbackContext, JobQueue
  File "/home/hendrik/.local/lib/python3.8/site-packages/telegram/ext/__init__.py", line 21, in <module>
    from .dispatcher import Dispatcher, DispatcherHandlerStop, run_async
  File "/home/hendrik/.local/lib/python3.8/site-packages/telegram/ext/dispatcher.py", line 33, in <module>
    from telegram import TelegramError
ImportError: cannot import name 'TelegramError' from 'telegram' (/home/hendrik/.local/lib/python3.8/site-packages/telegram/__init__.py)

**Comment by mkdryden** [comment]
I have not been able to reproduce this on either Ubuntu or Windows with any python version between 3.8 and 3.10, installing with either pip or Poetry, so I'm not sure what happened.
Just in case, I have updated the python-telegram-bot requirement to the latest, in case some old version of it in your environment was causing the problem, and updated the poetry lock file to the latest compatible version of everything, in [v0.6.4](https://github.com/mkdryden/telegram-stats-bot/commit/e8ecfab46678479ecec6d4847fc0844bf3515624).

**Comment by TheLexoPlexx** [comment]
I stumbled upon this same error in Python 3.8 when I accidentally installed the `python-telegram-bot` alongside the `telegram`-package. Uninstalling both and reinstallong only the required one did the trick.

**Comment by mkdryden** [comment]
> I stumbled upon this same error in Python 3.8 when I accidentally installed the `python-telegram-bot` alongside the `telegram`-package. Uninstalling both and reinstallong only the required one did the trick.

Ah, this makes sense. The `telegram` package seems to be some other defunct project with packages still on pypi and they share the same import names. I don't think there is any reason to use this package for anything, but I guess if you do, then it should be isolated from telegram-stats-bot by using a different venv/conda environment/etc.

**Comment by ldhuy-proj** [comment]
> I stumbled upon this same error in Python 3.8 when I accidentally installed the `python-telegram-bot` alongside the `telegram`-package. Uninstalling both and reinstallong only the required one did the trick.

This really solved the problem for me, we only need the package `python-telegram-bot`
